---
title: "Case Study 10"
author: Yvonne Huang
date: August 1, 2020
output: github_document
---
# library
```{r}
library(raster)
library(rasterVis)
library(rgdal)
library(ggmap)
library(tidyverse)
library(knitr)

# New Packages
library(ncdf4) # to import data from netcdf format

```


# Create afolder to hold the downloaded data
```{r}
dir.create("data",showWarnings = F) #create a folder to hold the data

lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"
lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"
```

# download them
```{r}
download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")

lulc=stack("data/MCD12Q1.051_aid0001.nc",varname="Land_Cover_Type_1")
lst=stack("data/MOD11A2.006_aid0001.nc",varname="LST_Day_1km")
# plot(lulc)
lulc=lulc[[13]]



Land_Cover_Type_1 = c(
  Water = 0, 
  `Evergreen Needleleaf forest` = 1, 
  `Evergreen Broadleaf forest` = 2,
  `Deciduous Needleleaf forest` = 3, 
  `Deciduous Broadleaf forest` = 4,
  `Mixed forest` = 5, 
  `Closed shrublands` = 6,
  `Open shrublands` = 7,
  `Woody savannas` = 8, 
  Savannas = 9,
  Grasslands = 10,
  `Permanent wetlands` = 11, 
  Croplands = 12,
  `Urban & built-up` = 13,
  `Cropland/Natural vegetation mosaic` = 14, 
  `Snow & ice` = 15,
  `Barren/Sparsely vegetated` = 16, 
  Unclassified = 254,
  NoDataFill = 255)

lcd=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(lcd))
```

# convert to raster (easy)
```{r}
lulc=as.factor(lulc)
```

# update the RAT with a left join
```{r}
levels(lulc)=left_join(levels(lulc)[[1]],lcd)


offs(lst)=-273.15
plot(lst[[1:10]])

tdates=names(lst)%>%
  sub(pattern="X",replacement="")%>%
  as.Date("%Y.%m.%d")

names(lst)=1:nlayers(lst)
lst=setZ(lst,tdates)

```
# PART 1 
```{r}
lw = SpatialPoints(data.frame(x= -78.791547,y=43.007211))
projection(lw) <- "+proj=longlat"
lw = spTransform(lw, CRSobj = crs(lst, asText = TRUE))
lst_transpose <- t(raster::extract(lst,lw,buffer=1000,fun=mean,na.rm=T) )

part1 <- data.frame(getZ(lst), lst_transpose)
colnames(part1) <- c("date", "value") 

graphics.off()
ggplot(part1, aes(date, value))+
  geom_point()+
  geom_smooth(n = 100, span = 0.01)
```
# PART2
```{r}
tmonth <- as.numeric(format(getZ(lst),"%m"))
lst_month <- stackApply(lst,tmonth , fun = mean)
names(lst_month)=month.name
gplot(lst_month)+
  geom_raster(aes(fill = value))
cellStats(lst_month,mean)
```

#PART 3 
```{r}
lulc2 = resample(lulc, lst, method="ngb")

lcds1=cbind.data.frame(
values(lst_month),
ID=values(lulc2[[1]]))%>%
na.omit()
temp=lcds1%>%gather(key='month',value='value',-ID)
temp=temp%>%mutate(ID=as.numeric(ID),month=factor(month,levels=month.name,ordered=T))
result=left_join(temp,lcd,by='ID')%>%filter(landcover %in% c('Urban & built-up','Deciduous Broadleaf forest'))
ggplot(result)+
  geom_point(aes(month,value))+
  theme_bw()+
  facet_wrap(~landcover)

```