---
title: "case study 08"
author: "Yvonne Huang"
date: "2022-10-25"
output: 
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---

```{r eval = FALSE, include=FALSE}
rmarkdown::render("CS_8.Rmd", output_format = "all") 
```

## R Markdown

```{r ,results='hide',message=FALSE}
library(tidyverse)
library(ggplot2)
library(kableExtra)

link = "ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt"
data <- read.table(link, skip = 57)
colnames(data) <- c("year", "mean", "unc")
```

```{r ,message=FALSE}
ggplot(data, aes(year,mean))+
  geom_smooth()+
  geom_point()+
  ggtitle("Mean CO2 trend 1959-2021")+
  xlab("year")+
  ylab("Mean annual CO2(ppm)")+
  theme(plot.title = element_text(hjust = 0.5))

top_5 <- arrange(data, desc(mean))[1:5,]
kable(top_5,
      caption = "Top 5 mean CO2 in 1959-2021",
      col.names = c("Year", "Mean", "Unc")) %>%
  kable_styling(
    latex_options = c("striped", "scale_down")
    )%>%
  row_spec(1, color = "red")
 
```


```{r}
decade <-  data %>%
  mutate(decade = floor(year/10)*10) %>% 
  group_by(decade) %>%
  slice_max(order_by = mean) %>%
  arrange(desc(mean))
  
kable(decade,
      caption = "Top mean CO2 in each decade",
      col.names = c("Year", "Mean", "Unc", "Decade")) %>%
  kable_styling(
    latex_options = c("striped", "scale_down")
    )%>%
  row_spec(1, color = "red") 
  

```

